// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60z7ABDvcmi7CtEeeX7lC6ubakBpZWDw',
    appId: '1:849280654960:android:9422544d2933b4a16e5eb5',
    messagingSenderId: '849280654960',
    projectId: 'medistats-20808',
    storageBucket: 'medistats-20808.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFNkrsB-eGt7IKS5K-TbMifPMc1bfuN0',
    appId: '1:849280654960:ios:4186b89b2f25d2de6e5eb5',
    messagingSenderId: '849280654960',
    projectId: 'medistats-20808',
    storageBucket: 'medistats-20808.firebasestorage.app',
    iosBundleId: 'com.example.medistats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGFNkrsB-eGt7IKS5K-TbMifPMc1bfuN0',
    appId: '1:849280654960:ios:4186b89b2f25d2de6e5eb5',
    messagingSenderId: '849280654960',
    projectId: 'medistats-20808',
    storageBucket: 'medistats-20808.firebasestorage.app',
    iosBundleId: 'com.example.medistats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWxDwrTLjjssZKzkwFzYFQc_w57yGR6M0',
    appId: '1:849280654960:web:30179834d9a36eb96e5eb5',
    messagingSenderId: '849280654960',
    projectId: 'medistats-20808',
    authDomain: 'medistats-20808.firebaseapp.com',
    storageBucket: 'medistats-20808.firebasestorage.app',
    measurementId: 'G-TQHGWQD2GM',
  );
}
